import {
  ADD_TO_PLAYLIST,
  REMOVE_FROM_PLAYLIST,
  PLAY_VIDEO,
} from "../actions/utility/types";

const initialState = {
  authenticated: false,
  playlist: [
    {
      id: " 7cyeD",
      videoId: "ayb9cfELqd0",
      title: "Fado",
      channelTitle: "Milky Chance - Topic",
      description:
        "Provided to YouTube by Universal Music Group\n\nFado · Milky Chance\n\nMind The Moon\n\n℗ A Vertigo Berlin recording; ℗ 2019 Muggelig Records GmbH, under exclusive license to Universal Music GmbH\n\nReleased on: 2019-11-15\n\nProducer: Milky Chance\nProducer, Associated  Performer, Programming: Tobias Felix Kuhn\nStudio  Personnel, Mixer: Rob Kinelski\nStudio  Personnel, Mastering  Engineer: Hans-Philipp Graf\nAssociated  Performer, Vocals: Clemens Rehbein\nAssociated  Performer, Background  Vocalist: Philipp Dausch\nAssociated  Performer, Guitar: Antonio Greger\nComposer  Lyricist: Clemens Rehbein\nComposer  Lyricist: Philipp Dausch\nComposer: Tobias Felix Kuhn\n\nAuto-generated by YouTube.",
      date: "2019-11-14T10:04:05Z",
      thumbnail: {
        url: "https://i.ytimg.com/vi/ayb9cfELqd0/hqdefault.jpg",
        width: 480,
        height: 360,
      },
    },
  ],
  currentlyPlaying: {
    id: " 7cyeD",
    videoId: "ayb9cfELqd0",
    title: "Fado",
    channelTitle: "Milky Chance - Topic",
    description:
      "Provided to YouTube by Universal Music Group\n\nFado · Milky Chance\n\nMind The Moon\n\n℗ A Vertigo Berlin recording; ℗ 2019 Muggelig Records GmbH, under exclusive license to Universal Music GmbH\n\nReleased on: 2019-11-15\n\nProducer: Milky Chance\nProducer, Associated  Performer, Programming: Tobias Felix Kuhn\nStudio  Personnel, Mixer: Rob Kinelski\nStudio  Personnel, Mastering  Engineer: Hans-Philipp Graf\nAssociated  Performer, Vocals: Clemens Rehbein\nAssociated  Performer, Background  Vocalist: Philipp Dausch\nAssociated  Performer, Guitar: Antonio Greger\nComposer  Lyricist: Clemens Rehbein\nComposer  Lyricist: Philipp Dausch\nComposer: Tobias Felix Kuhn\n\nAuto-generated by YouTube.",
    date: "2019-11-14T10:04:05Z",
    thumbnail: {
      url: "https://i.ytimg.com/vi/ayb9cfELqd0/hqdefault.jpg",
      width: 480,
      height: 360,
    },
  },
};

export const appReducer = (state = initialState, action) => {
  switch (action.type) {
    case ADD_TO_PLAYLIST:
      return { ...state, playlist: [...state.playlist, action.payload] };

    case REMOVE_FROM_PLAYLIST:
      let newPlaylist = [...state.playlist].filter(
        (playlist) => playlist.id !== action.payload
      );
      return { ...state, playlist: newPlaylist };

    case PLAY_VIDEO:
      return { ...state, currentlyPlaying: action.payload };

    default:
      return state;
  }
};
